MODULE_TOPDIR = ../..

PGM = r.los

LIBES = $(SEGMENTLIB) $(GPROJLIB) $(GISLIB)
DEPENDENCIES = $(SEGMENTDEP) $(GPROJDEP) $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
