
MODULE_TOPDIR = ../..

PGM = v.in.region

include $(MODULE_TOPDIR)/include/Make/Module.make

DEPENDENCIES = $(VECTORDEP) $(GISDEP)

LIBES = $(VECTORLIB) $(GISLIB)

EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

default: cmd

