MODULE_TOPDIR = ../../..

EXTRA_LIBS=$(GISLIB) $(RASTERLIB)

LIB_NAME = grass_rli
PGM = r.li.daemon

DEPENDENCIES = $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib
