
MODULE_TOPDIR = ../..

PGM = v.what

LIBES        = $(VECTLIB) $(FORMLIB) $(DBMILIB) $(GISLIB)

DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(FORMDEP) $(GISDEP)

EXTRA_CFLAGS = $(VECT_CFLAGS)
EXTRA_INC = $(VECT_INC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




