# This script created by the script_file_tools program
global Nv_mapLoopMode Nv_mapLoopFile
set Nv_mapLoopMode 0
set Nv_mapLoopFile ""
SendScriptLine "Nunset_cancel_func"

proc pad { x } {
 while {[string length "$x"] < 5} {
  set x "0$x"
 }
 return $x
}


# Start of file sequence code
SendScriptLineWait "load_state_aux /data/stimpy/terry/tcl/nviz.new/test.state" script_play
set mhandle3 [ReturnMapHandle surf*827869142]
for {set iloop2 0} {$iloop2 < 5} {incr iloop2} {
 SendScriptLine "global NVIZ_BLANK_MAPS"
 SendScriptLine "set NVIZ_BLANK_MAPS {}"
 if {$iloop2 < 5} then {
  if {[lsearch {} $iloop2] == -1} then {
   if {[lsearch {} $iloop2] > -1}  then {
    SendScriptLine "lappend NVIZ_BLANK_MAPS [ExtractMapID $mhandle3]"
   } else {
    SendScriptLine "$mhandle3 set_att color [lindex {as20.fp@helenafp as30.fp@helenafp as60.fp@helenafp as80.fp@helenafp as90.fp@helenafp} $iloop2]"
   }
  }
 }
 # Image saving code here
 if {[catch {set Frame_Num}]} then { set Frame_Num 0 }
 SendScriptLine "Nsurf_draw_all"
 SendScriptLine "Nvect_draw_all"
 SendScriptLine "Nsite_draw_all"
 SendScriptLine "Nwrite_ppm timages[pad $Frame_Num].ppm"
 incr Frame_Num
 after 1000
}

