MODULE_TOPDIR = ../../..

LIBES = $(TEMPORALLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(TEMPORALDEP) $(DBMIDEP) $(GISDEP)

PGM = t.connect

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

