
CC = gcc
CFLAGS = 

OBJECTS = card.o \
	gammavol.o \
	index.o \
	node.o \
	rect.o \
	sphvol.o \
	split.o 

all: librtree.a test

librtree.a: $(OBJECTS)
	ar rcv librtree.a $(OBJECTS)
	ranlib librtree.a

test: test.c librtree.a
	$(CC) $(LDFLAGS) -o $@ test.c librtree.a -lm

.c.o:
	$(CC) $(CFLAGS) -Wall -c $<

clean:
	rm -rf ./*.o ./*.a ./test

