MODULE_TOPDIR = ../..

PGM = i.cca

LIBES     = $(IMAGERYLIB) $(GMATHLIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GMATHDEP) $(GISDEP) $(RASTRDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
