MODULE_TOPDIR = ../..

PGM = i.cca

LIBES     = $(IMAGERYLIB) $(GMATHLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GMATHDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
