MODULE_TOPDIR = ../..

PGM=v.net.bridge

LIBES = $(VECTORLIB) $(GISLIB) $(NETALIB)
DEPENDENCIES = $(VECTORDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	
