MODULE_TOPDIR = ..

SUBDIRS = \
	t.connect \
	t.create \
	t.support \
	t.topology \
	t.list \
	t.info \
	t.merge \
	t.remove \
	t.sample \
	t.register \
	t.unregister \
	t.rast.accumulate \
	t.rast.accdetect \
	t.rast.aggregate \
	t.rast.aggregate.ds \
	t.rast.colors \
	t.rast.contour \
	t.rast.to.rast3 \
	t.rast.univar \
	t.rast.list \
	t.rast.mapcalc \
	t.rast.algebra \
	t.rast.neighbors \
	t.rast.series \
	t.rast.export \
	t.rast.out.vtk \
	t.rast.import \
	t.rast.gapfill \
	t.rast.extract \
	t.rast.to.vect \
	t.rast.what \
	t.rast3d.list \
	t.rast3d.extract \
	t.rast3d.mapcalc \
	t.rast3d.algebra \
	t.rast3d.univar \
	t.rename \
	t.select \
	t.snap \
	t.shift \
	t.vect.list \
	t.vect.db.select \
	t.vect.export \
	t.vect.extract \
	t.vect.algebra \
	t.vect.import \
	t.vect.what.strds \
	t.vect.observe.strds \
	t.vect.univar

PGM = temporalintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

