MODULE_TOPDIR = ../..

PGM = d.where

LIBES = $(DISPLAYLIB) $(GPROJLIB) $(GISLIB)
DEPENDENCIES = $(DISPLAYDEP) $(GPROJDEP) $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
