MODULE_TOPDIR = ../..

PGM = i.svm.train

LIBES = $(RASTERLIB) $(IMAGERYLIB) $(GISLIB)
DEPENDENCIES = $(RASTERDEP) $(IMAGERYDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
