---

default: true

# Fix any fixable errors (depending on the markdownlint wrapper tool used)
fix: true

MD041: false # first-line-h1

# Errors from .html to .md rename (first step in HTML to Markdown conversion)
no-duplicate-heading: false
heading-increment: false
no-inline-html: false
no-alt-text: false
line-length: false
# The block above this is to be eventually removed.

no-emphasis-as-heading: false
link-fragments: false
no-space-in-links: false
