---

default: true

# Fix any fixable errors (depending on the markdownlint wrapper tool used)
fix: true

MD041: false # first-line-h1
line-length:
  code_blocks: false
  tables: false
  line_length: 120

no-inline-html:
  allowed_elements: [sup]
