
MODULE_TOPDIR = ../..

PGM=v.select

LIBES        = $(VECTLIB) $(VECTLIB_REAL) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(GISDEP)
EXTRA_INC    = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

