MODULE_TOPDIR = ../..

PGM = r.spreadpath

LIBES = $(SEGMENTLIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES = $(SEGMENTDEP) $(GISDEP) $(RASTRDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
