MODULE_TOPDIR = ../..

PGM=r3.gwflow

LIBES = $(GPDELIB) $(G3DLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES = $(GPDEDEP) $(G3DDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
