MODULE_TOPDIR = ..

SUBDIRS = \
	i.albedo \
	i.aster.toar \
	i.atcorr \
	i.biomass \
	i.cca \
	i.cluster \
	i.eb.evapfr \
	i.eb.eta \
	i.eb.h_sebal01 \
	i.eb.netrad \
	i.eb.soilheatflux \
	i.evapo.mh \
	i.evapo.pm \
	i.evapo.pt \
	i.evapo.time \
	i.emissivity \
	i.find \
	i.gensig \
	i.gensigset \
	i.group \
	i.his.rgb \
	i.landsat.toar \
	i.landsat.acca \
	i.latlong \
	i.maxlik \
	i.modis.qc \
	i.ortho.photo \
	i.rectify \
	i.rgb.his \
	i.segment \
	i.smap \
	i.sunhours \
	i.target \
	i.topo.corr \
	i.pca \
	i.vi \
	i.fft \
	i.ifft \
	i.zc

PGM = imageryintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

