# SPDX-License-Identifier: GPL-2.0-or-later
MODULE_TOPDIR = ../..


LIB = SEGMENT

LIBES = $(BTREE2LIB)

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=segment
