
MODULE_TOPDIR = ../..

PGM=v.to.rast3

LIBES     = $(VECTLIB) $(DBMILIB) $(G3DLIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(G3DDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)
 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

