MODULE_TOPDIR = ../../..

PGM = r.watershed.ram

LIBES = $(RASTERLIB) $(GISLIB) $(MATHLIB) $(BTREE2LIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Etc.make
include $(MODULE_TOPDIR)/include/Make/NoHtml.make

default: etc 
