# SPDX-License-Identifier: GPL-2.0-or-later
MODULE_TOPDIR = ../..

include $(MODULE_TOPDIR)/include/Make/Vars.make

#order is relevant:
SUBDIRS = \
	SQL \
	lib \

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: subdirs
