MODULE_TOPDIR = ../..

PGM = r3.in.bin

LIBES = $(RASTERLIB) $(RASTER3DLIB) $(GISLIB)
DEPENDENCIES = $(RASTERDEP) $(RASTER3DDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
