MODULE_TOPDIR = ../..

PGM = i.rectify

LIBES = $(IMAGERYLIB) $(RASTERLIB) $(GISLIB)
DEPENDENCIES = $(IMAGERYDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
