MODULE_TOPDIR = ../../..

PGM=test.gmath.lib

LIBES = $(GISLIB) $(GMATHLIB) $(OMPLIB)
DEPENDENCIES = $(GISDEP) $(GMATHDEP) $(OMPDEP)
EXTRA_CFLAGS = $(OMPCFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
