MODULE_TOPDIR = ../..

PGM = i.points

LIBES     = $(IMAGERYLIB) $(DISPLAYLIB) $(GMATHLIB) $(GISLIB) $(CURSES)
DEPENDENCIES= $(IMAGERYDEP) $(DISPLAYDEP) $(GMATHDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
