MODULE_TOPDIR = ../..

PGM = i.rgb.his

LIBES     = $(IMAGERYLIB) $(GISLIB) $(RASTRLIB) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GISDEP) $(RASTRDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
