MODULE_TOPDIR = ../../..

PGM = r.watershed.seg

LIBES = $(SEGMENTLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(SEGMENTDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Etc.make
include $(MODULE_TOPDIR)/include/Make/NoHtml.make

default: etc

