MODULE_TOPDIR = ../../..

PGM = r.watershed.seg

LIBES = $(GISLIB) $(SEGMENTLIB)
DEPENDENCIES = $(GISDEP) $(SEGMENTDEP)

include $(MODULE_TOPDIR)/include/Make/Etc.make
include $(MODULE_TOPDIR)/include/Make/NoHtml.make

default: etc

