# SPDX-License-Identifier: GPL-2.0-or-later
MODULE_TOPDIR = ../..

LIB = RASTER3D

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=raster3d
