MODULE_TOPDIR = ../..

PGM=v.net.components

LIBES = $(VECTORLIB) $(GISLIB) $(NETALIB) $(DBMILIB)
DEPENDENCIES = $(VECTORDEP) $(GISDEP) $(DBMIDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	
