
MODULE_TOPDIR = ../..

PGM=v.vect.stats

LIBES = $(VECTORLIB) $(STATSLIB) $(GISLIB)
DEPENDENCIES= $(VECTORDEP) $(STATSDEP) $(GISDEP)

EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

