MODULE_TOPDIR = ../..

PGM = r.resamp.stats

LIBES = $(STATSLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(STATSDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
