MODULE_TOPDIR = ../..

PGM = r.param.scale

LIBES = $(GMATHLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(GMATHDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
