MODULE_TOPDIR = ../..

PGM = v.mapcalc

LIBES = $(MATHLIB)
DEPENDENCIES = 

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

.INTERMEDIATE: v.mapcalc.tab.c v.mapcalc.tab.h v.mapcalc.output
