MODULE_TOPDIR = ../..

PGM = r3.neighbors

LIBES = $(RASTERLIB) $(RASTER3DLIB) $(GISLIB) $(STATSLIB)
DEPENDENCIES = $(RASTERDEP) $(RASTER3DDEP) $(GISDEP) $(STATSDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
