MODULE_TOPDIR = ../..

PGM = i.gensigset

LIBES     = $(IMAGERYLIB) $(GISLIB) $(RASTERLIB) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GISDEP) $(RASTERDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
