MODULE_TOPDIR = ../../..

PGM=test.g3d.lib

LIBES = $(GISLIB) $(RASTER3DLIB) $(RASTERLIB) 
DEPENDENCIES = $(GISDEP) $(RASTER3DDEP) $(RASTERDEP) 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
