MODULE_TOPDIR = ../../..

PGM = r.li.padcv

EXTRA_CLEAN_DIRS=doxygenhtml



LIBES = $(RLILIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)

DEPENDENCIES = $(RLIDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

