MODULE_TOPDIR = ../..

LIB_NAME = $(CDHC_LIBNAME)

LIB_OBJS = \
	dcmp.o \
        enormp.o normp.o xinormal.o \
        omnibus.o geary.o extreme.o dagstndn.o kuiprsvn.o \
        watsonun.o durbins.o andrsndn.o cvmw2n.o ksn.o \
        dmax.o dmaxe.o chisqn.o shapiro1.o shapiro2.o shapiroe.o \
        cvmw2e.o kse.o kuiprsve.o watsonue.o andrsnde.o \
        chisqe.o kotz.o \
        royston.o as181.o as177.o as241.o as66.o \
        weisberg.o

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib
