MODULE_TOPDIR = ../../..

PGM=test.gparson.lib

LIBES = $(PARSONLIB) $(GPARSONLIB) $(GISLIB)
DEPENDENCIES = $(PARSONDEP) $(GPARSONDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd