MODULE_TOPDIR = ../..

PGM = r.surf.random

LIBES = $(GMATHLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(GMATHDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
