MODULE_TOPDIR = ../..

PGM = r.surf.random

LIBES = $(GMATHLIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES = $(GMATHDEP) $(GISDEP) $(RASTRDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
