MODULE_TOPDIR = ../../..

PGM = r.li.mps

EXTRA_CLEAN_DIRS=doxygenhtml



LIBES = $(GISLIB) $(RASTERLIB) $(RLILIB)

DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(RLIDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

