MODULE_TOPDIR = ../..

PGM = r.sun

LIBES =  $(GPROJLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(GPROJDEP) $(GISDEP) $(RASTERDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
