
MODULE_TOPDIR = ../..

PGM=v.to.rast

LIBES     = $(VECTLIB) $(DBMILIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(GISDEP) $(RASTRDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)
 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

