MODULE_TOPDIR = ..

SUBDIRS = icons scripts xml tcltk wxpython

include $(MODULE_TOPDIR)/include/Make/Platform.make

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

clean: cleansubdirs

