MODULE_TOPDIR = ../..

EXTRA_LIBS=$(GISLIB)
LIB_NAME = $(ROWIO_LIBNAME)

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

DOXNAME = rowiolib
