
MODULE_TOPDIR = ../..

PGM = g.remove

include $(MODULE_TOPDIR)/include/Make/Module.make

LIBES = $(MANAGELIB) $(VECTLIB) $(DBMILIB) $(GISLIB) $(G3DLIB)
DEPENDENCIES = $(GISDEP) $(VECTDEP) $(DBMIDEP) $(MANAGEDEP) $(G3DDEP)

default: cmd

