MODULE_TOPDIR = ../..

PGM = r.surf.fractal

LIBES = $(GMATHLIB) $(GISLIB) $(FFTWLIB)
DEPENDENCIES = $(GMATHDEP) $(GISDEP)
EXTRA_INC = $(FFTWINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
