MODULE_TOPDIR = ../../..

PGM = r.li.padrange

EXTRA_CLEAN_DIRS=doxygenhtml



LIBES = $(RLILIB) $(RASTERLIB) $(GISLIB)

DEPENDENCIES = $(RLIDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
