MODULE_TOPDIR = ../..


EXTRA_CFLAGS = $(FFTWINC)

LIB = GMATH

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=gmath
