MODULE_TOPDIR = ../..

PGM = d.rgb

LIBES  = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB)
DEPLIBS= $(DEPD_LIB) $(DEPDISPLAYLIB) $(DEPRASTERLIB) $(DEPGISLIB)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
