MODULE_TOPDIR = ../..

PGM = r.param.scale

LIBES = $(GISLIB) $(RASTRLIB) $(GMATHLIB)
DEPENDENCIES = $(GISDEP) $(RASTRDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
