MODULE_TOPDIR = ../..

PGM = r.param.scale

LIBES = $(GISLIB) $(RASTERLIB) $(GMATHLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
