MODULE_TOPDIR = ../..

PGM = d.linegraph

LIBES = $(DISPLAYLIB) $(SYMBLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(DISPLAYDEP) $(SYMBDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
