MODULE_TOPDIR = ../../..

PGM = test.octree.lib

LIBES = $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(GISDEP)
EXTRA_INC = -I..
EXTRA_CFLAGS =

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
