MODULE_TOPDIR = ../../..

include $(MODULE_TOPDIR)/include/Make/Other.make

FILES = wxGUI \
	wxGUI.Vector_Digitizing_Tool \
	wxGUI.Attribute_Table_Manager \
	wxGUI.Nviz

default: $(patsubst %,$(HTMLDIR)/%.html,$(FILES))
