#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Other GRASS authors
# SPDX-License-Identifier: GPL-2.0-or-later
"""Convert generated GRASS Markdown documentation to a man page.

Usage: VERSION_NUMBER=x.y.z g.md2man.py input.md output.1

The input is a file produced by mkmarkdown.py (or any of the generated
index pages). The MkDocs content tabs are reduced to the command line
variant: man pages document the command line interface, and the Python
API tabs only repeat the same parameters in Python syntax.
"""

import os
import re
import sys
from io import StringIO
from pathlib import Path

try:
    # When installed, ggroff.py sits next to this script in $GISBASE/utils.
    from ggroff import Formatter
except ImportError:
    # In the source tree it lives in the sibling g.html2man directory.
    sys.path.append(str(Path(__file__).resolve().parent.parent / "g.html2man"))
    from ggroff import Formatter

import gmd

CLI_TAB_TITLE = "Command line"
# The Python API tabs are matched by prefix so that both the current
# "Python (grass.tools)" and "Python (grass.script)" tabs, and any future
# variant, are recognized. These titles come from lib/gis/parser_md.c.
PYTHON_TAB_PREFIX = "Python ("


def transform_tabs(nodes):
    """Replace tabs nodes according to the man page tab policy.

    A tab group generated by --md-description (one with a command line
    tab) is replaced by the content of the command line tab. In any other
    group (e.g., hand-written examples) the Python API tabs are dropped
    and each remaining tab becomes a subsection titled after the tab.
    """
    out = []
    for node in nodes:
        if isinstance(node, tuple):
            tag, attrs, body = node
            if tag == "tabs":
                out.extend(expand_tabs(body))
                continue
            if isinstance(body, list):
                node = (tag, attrs, transform_tabs(body))
        out.append(node)
    return out


def expand_tabs(tabs):
    has_cli = any(dict(attrs).get("title") == CLI_TAB_TITLE for _, attrs, _ in tabs)
    out = []
    for _tag, attrs, body in tabs:
        title = dict(attrs).get("title")
        if title and title.startswith(PYTHON_TAB_PREFIX):
            continue
        if has_cli and title != CLI_TAB_TITLE:
            # A generated group (one with a command line tab) should only
            # contain the command line and Python tabs; anything else means
            # the producer's tab titles drifted from what is expected here.
            sys.stderr.write(f"warning: unexpected tab in generated group: {title}\n")
        if not has_cli:
            out.append(("h4", [], [title]))
        out.extend(transform_tabs(body))
    return out


def plain_text(content):
    """Extract the text of a tree fragment, ignoring markup."""
    if isinstance(content, str):
        return content
    if isinstance(content, tuple):
        return plain_text(content[2])
    if isinstance(content, list):
        return "".join(plain_text(item) for item in content)
    return ""


def normalized_text(content):
    return " ".join(plain_text(content).split())


def is_tag(node, *tags):
    return isinstance(node, tuple) and node[0] in tags


def build_document(meta, nodes, fallback_name):
    """Assemble the final tree with NAME/KEYWORDS/SYNOPSIS sections."""
    nodes = transform_tabs(nodes)
    heading = nodes.pop(0) if nodes and is_tag(nodes[0], "h1") else None
    name = meta.get("name", fallback_name)
    description = meta.get("description")
    if not ("name" in meta and description):
        # Index and overview pages: keep the page heading as a section.
        if heading:
            nodes.insert(0, ("h2", heading[1], heading[2]))
        return name, nodes

    # NAME and KEYWORDS content is emitted as plain text rather than
    # paragraphs to avoid .PP macros directly under the section headings.
    out = [
        ("h2", [], ["NAME"]),
        "\n",
        ("b", [], [name]),
        " - " + description,
    ]
    # The paragraphs between the heading and the synopsis repeat the
    # description from the front matter; drop them to match the layout
    # of a man page NAME section.
    while (
        nodes
        and is_tag(nodes[0], "p")
        and normalized_text(nodes[0]) in normalized_text(description)
    ):
        nodes.pop(0)
    if meta.get("keywords"):
        out.extend([("h2", [], ["KEYWORDS"]), "\n" + ", ".join(meta["keywords"])])
    # The generated usage (the former command line tab) has no heading
    # of its own; in a man page it is the SYNOPSIS. The bare name and
    # --help lines are man page conventions kept from the previous
    # HTML-based pages.
    if nodes and not is_tag(nodes[0], "h2", "h3", "h4"):
        out.extend(
            [
                ("h2", [], ["SYNOPSIS"]),
                "\n",
                ("b", [], [name]),
                ("br", [], None),
                ("b", [], [name + " --help"]),
                ("br", [], None),
            ]
        )
    return name, out + nodes


def main():
    infile = Path(sys.argv[1])
    meta, nodes = gmd.parse(infile.read_text(encoding="UTF-8"))
    name, tree = build_document(meta, nodes, infile.name.removesuffix(".md"))

    stream = StringIO()
    Formatter(str(infile), stream).pp(tree)
    text = stream.getvalue()

    # Strip excess whitespace (same cleanup as g.html2man).
    text = re.sub(r"[ \t\n]*\n([ \t]*\n)*", "\n", text).lstrip()

    version = os.environ.get("VERSION_NUMBER", "")
    title = f'.TH {name} 1 "" "GRASS {version}" "GRASS User\'s Manual"\n'
    Path(sys.argv[2]).write_bytes((title + text).encode("UTF-8"))


if __name__ == "__main__":
    main()
