"""Paths to resources and and other GRASS properties, configured during build

(C) 2025 by Nicklas Larsson and the GRASS Development Team

SPDX-License-Identifier: GPL-2.0-or-later


This is not a stable part of the API. Use at your own risk.

The "@...@" variables are being substituted during build process

"""

GRASS_VERSION = "@GRASS_VERSION_NUMBER@"
GRASS_VERSION_MAJOR = "@GRASS_VERSION_MAJOR@"
GRASS_VERSION_MINOR = "@GRASS_VERSION_MINOR@"
LD_LIBRARY_PATH_VAR = "@LD_LIBRARY_PATH_VAR@"
CONFIG_PROJSHARE = "@CONFIG_PROJSHARE@"
GRASS_EXE_NAME = "@START_UP@"
GRASS_VERSION_GIT = "@GRASS_VERSION_GIT@"

GRASS_PREFIX = "@GRASS_PREFIX@"
GISBASE = "@GISBASE_INSTALL_PATH@"

GRASS_COLORSDIR = "@GRASS_COLORSDIR@"
GRASS_DOCDIR = "@GRASS_DOCDIR@"
GRASS_ETCBINDIR = "@GRASS_ETCBINDIR@"
GRASS_ETCDIR = "@GRASS_ETCDIR@"
GRASS_FONTSDIR = "@GRASS_FONTSDIR@"
GRASS_GRAPHICSDIR = "@GRASS_GRAPHICSDIR@"
GRASS_GUIRESDIR = "@GRASS_GUIRESDIR@"
GRASS_GUISCRIPTDIR = "@GRASS_GUISCRIPTDIR@"
GRASS_GUIWXDIR = "@GRASS_GUIWXDIR@"
GRASS_LOCALEDIR = "@GRASS_LOCALEDIR@"
GRASS_MISCDIR = "@GRASS_MISCDIR@"
GRASS_MKDOCSDIR = "@GRASS_MKDOCSDIR@"
