MODULE_TOPDIR = ../..

PGM = i.ask

LIBES     = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB)
DEPENDENCIES= $(DISPLAYDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: etc

htmletc:
	@echo no docs needed for $(PGM)
