MODULE_TOPDIR = ../..

PGM = r.sunmask

LIBES = $(GPROJLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(GPROJDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
