MODULE_TOPDIR = ../..

SUBDIRS = \
	v.surf.bspline \
	v.outlier \
	v.lidar.correction \
	v.lidar.edgedetection \
	v.lidar.growing \
        r.resamp.bspline

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

