MODULE_TOPDIR = ../../..

EXTRA_LIBS = $(GISLIB) $(DBMILIB) $(DATETIMELIB)
# needed? $(OMPLIBPATH)

LIB = TEMPORAL

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=temporal
