MODULE_TOPDIR = ../..

PGM = r.surf.contour

LIBES = $(SEGMENTLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(SEGMENTDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
