MODULE_TOPDIR = ../..

PGM = r.surf.contour

LIBES = $(SEGMENTLIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES = $(SEGMENTDEP) $(GISDEP) $(RASTRDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
