
MODULE_TOPDIR = ../..

PGM = v.net.alloc

LIBES = $(VECTORLIB) $(GISLIB) $(GRAPHLIB)
DEPENDENCIES = $(VECTORDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




