MODULE_TOPDIR = ../..

PGM = i.latlong

LIBES = $(GPROJLIB) $(RASTERLIB) $(GISLIB) $(PROJLIB)
DEPENDENCIES = $(GPROJDEP) $(RASTERDEP) $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make


default: cmd
