MODULE_TOPDIR = ../..

EXTRA_CFLAGS=-I../driver

EXTRA_LIBS=$(DRIVERLIB) $(GISLIB) $(MATHLIB)
LIB_NAME = $(HTMLDRIVER_LIBNAME)
PGM = htmldriver

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib
