MODULE_TOPDIR = ../../..

LIB = IORTHO

LIBES     = $(IMAGERYLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib
