
MODULE_TOPDIR = ../..

PGM = v.what

LIBES = $(VECTORLIB) $(DBMILIB) $(GISLIB)

DEPENDENCIES = $(VECTORDEP) $(DBMIDEP) $(GISDEP)

EXTRA_CFLAGS = $(VECT_CFLAGS)
EXTRA_INC = $(VECT_INC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




