export GRASS_PROJSHARE=@GRASS_PROJSHARE@
export PROJ_LIB=@PROJ_LIB@
export GDAL_DATA=@GDAL_DATA@
export GEOTIFF_CSV=@GEOTIFF_CSV@
export GRASS_PYTHON=@GRASS_PYTHON@
export GRASS_CONFIG_DIR=@GRASS_CONFIG_DIR@

# export PYTHONHOME=$GISBASE\Python37
# export FONTCONFIG_FILE=@GISBASE@\etc\fonts.conf
# export LD_LIBRARY_PATH=@DLL_PATH_LIST@:PATH%
