MODULE_TOPDIR = ..

SUBDIRS = \
	r3.cross.rast \
	r3.gwflow \
	r3.in.ascii \
	r3.in.bin \
	r3.in.v5d \
	r3.info \
	r3.mask \
	r3.mkdspf \
	r3.null \
	r3.neighbors \
	r3.out.ascii \
	r3.out.bin \
	r3.out.netcdf \
	r3.out.v5d \
	r3.out.vtk \
	r3.retile \
	r3.stats \
	r3.support \
	r3.timestamp \
	r3.to.rast \

PGM = raster3dintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

