
MODULE_TOPDIR = ..

SUBDIRS = \
	d.barscale \
	d.colorlist \
	d.colortable \
	d.erase \
	d.font \
	d.geodesic \
	d.graph \
	d.grid \
	d.his \
	d.histogram \
	d.info \
	d.labels \
	d.legend \
	d.linegraph \
	d.nviz \
	d.path \
	d.rast \
	d.rast.arrow \
	d.rast.num \
	d.rgb \
	d.rhumbline \
	d.text.new \
	d.title \
	d.vect \
	d.vect.chart \
	d.thematic.area \

#	d.colors \
#	d.extract \
#	d.measure \
#	d.profile \
#	d.what.rast \
#	d.what.vect \
#	d.where \
#	d.zoom \
#	drivers

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

clean: cleansubdirs

