
MODULE_TOPDIR = ..

PGM = displaydrivers

SUBDIRS = \
	d.barscale \
	d.colorlist \
	d.colortable \
	d.erase \
	d.font \
	d.fontlist \
	d.geodesic \
	d.graph \
	d.grid \
	d.his \
	d.histogram \
	d.info \
	d.labels \
	d.legend \
	d.linegraph \
	d.mon \
	d.northarrow \
	d.path \
	d.profile \
	d.rast \
	d.rast.arrow \
	d.rast.num \
	d.rgb \
	d.rhumbline \
	d.text \
	d.title \
	d.vect \
	d.vect.chart \
	d.thematic.area \
	d.where
#	d.colors \
#	d.extract \
#	d.measure \
#	d.what.rast \
#	d.what.vect \
#	d.zoom \

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs
