# SPDX-License-Identifier: GPL-2.0-or-later
MODULE_TOPDIR = ../../..

EXTRA_CFLAGS = $(USE_BUFFERED_IO)

LIB = DBMIBASE

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib $(ARCH_INCDIR)/dbstubs.h
