
MODULE_TOPDIR = ..

SUBDIRS = \
	drivers \
	db.columns \
	db.connect \
	db.copy \
	db.createdb \
	db.databases \
	db.describe \
	db.drivers \
	db.dropdb \
	db.droptable \
	db.execute \
	db.login \
	db.select \
	db.tables

PGM = databaseintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: subdirs

