MODULE_TOPDIR = ../..

PGM = r.horizon

LIBES =  $(GPROJLIB) $(GISLIB) $(RASTRLIB)
DEPENDENCIES = $(GPROJDEP) $(GISDEP) $(RASTRDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
