MODULE_TOPDIR = ../..

PGM = r.surf.idw2

LIBES = $(GISLIB) $(RASTERLIB) $(DATETIMELIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(DATETIMEDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
