MODULE_TOPDIR = ../..

PGM = r.surf.idw2

LIBES = $(GISLIB) $(RASTRLIB) $(DATETIMELIB)
DEPENDENCIES = $(GISDEP) $(RASTRDEP) $(DATETIMEDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
