MODULE_TOPDIR = ../..

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: $(ETC)/grass-interface.dtd 

$/$(ETC)/grass-interface.dtd : grass-interface.dtd 
	$(INSTALL_DATA) grass-interface.dtd $(ETC)/grass-interface.dtd 
