MODULE_TOPDIR = ../..

PGM = i.cluster

LIBES     = $(CLUSTERLIB) $(IMAGERYLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES= $(CLUSTERDEP) $(IMAGERYDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
