MODULE_TOPDIR = ../..

PGM = i.smap

LIBES = $(IMAGERYLIB) $(GMATHLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(IMAGERYDEP) $(GMATHDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




