"""Tests of the header emitted by g.parser --script

The header is produced by G__script() in lib/gis/parser_script.c.
"""

import os
import re

import pytest

import grass.script as gs
from grass.tools import Tools

TOOL = "v.what.rast"


@pytest.fixture(scope="module")
def session(tmp_path_factory):
    """Set up a GRASS session for the tests."""
    tmp_path = tmp_path_factory.mktemp("grass_session")
    project = "test_project"
    gs.create_project(tmp_path, project)
    with gs.setup.init(tmp_path / project, env=os.environ.copy()) as session:
        yield session


@pytest.fixture(scope="module")
def script(session):
    """Return the script generated by TOOL --script."""
    tools = Tools(session=session)
    return tools.run_cmd([TOOL, "--script"]).stdout


def test_script_header_has_no_obsolete_license_text(script):
    """The generated header carries no COPYRIGHT field and no GPL paragraph."""
    for obsolete in ("COPYRIGHT:", "free software", "GNU General Public License"):
        assert obsolete not in script, (
            f"Generated script still contains obsolete license text: {obsolete!r}"
        )


def test_script_header_has_one_holder_per_line(script):
    """Each copyright line names one holder, and the collective one comes last."""
    lines = script.splitlines()
    copyright_lines = [
        i for i, line in enumerate(lines) if "SPDX-FileCopyrightText:" in line
    ]
    identifiers = [
        i for i, line in enumerate(lines) if "SPDX-License-Identifier:" in line
    ]

    assert len(identifiers) == 1, "Expected exactly one SPDX-License-Identifier line."
    assert copyright_lines, "Expected at least one SPDX-FileCopyrightText line."
    assert max(copyright_lines) < identifiers[0], (
        "All SPDX-FileCopyrightText lines must precede SPDX-License-Identifier."
    )
    assert (
        lines[max(copyright_lines)] == "# SPDX-FileCopyrightText: Other GRASS authors"
    ), "The last copyright line must be the collective line."
    for i in copyright_lines:
        assert not re.search(r",\s+and\s|\sand\sthe\s", lines[i]), (
            f"Copyright line names more than one holder: {lines[i]!r}"
        )
