#!/bin/sh
# This program is free software under the GPL (>=v2)
# Read the COPYING file that comes with GRASS for details.

# the next line restarts using wish \
 exec "$GRASS_WISH" "$0" "$@"


# Simply ask if the selected area is ok or not and save
# the answer in the environment variable "env(name)"

    global env
    wm title . "Select this area"
    wm minsize . 250 100
    label .label -text "Is this area ok?"
    pack .label 
    frame .buttons
    pack .buttons
    set val ""
    button .buttons.ok -text "Ok" -command {
	exec echo 1 > $env(name).var
	destroy .
    }
    button .buttons.no -text "No" -command {
	exec echo 0 > $env(name).var
	destroy .
    }
    grid .buttons.ok .buttons.no
