MODULE_TOPDIR = ../..

PGM = r.neighbors

LIBES = $(STATSLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(STATSDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
