MODULE_TOPDIR = ../..

PGM = d.colors

LIBES     = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB) $(CURSES)
DEPENDENCIES= $(DISPLAYDEP) $(RASTERDEP) $(GISDEP) $(CURSESDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
