MODULE_TOPDIR = ../..

PGM = d.colors

LIBES     = $(DISPLAYLIB) $(RASTERLIB) $(GISLIB) $(CURSES)
DEPENDENCIES= $(DISPLAYDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
