MODULE_TOPDIR = ../..

PGM = d.profile

LIBES     = $(DISPLAYLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES= $(DISPLAYDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
