
MODULE_TOPDIR = ../..

PGM = d.vect.chart

LIBES        = $(DISPLAYLIB) $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(DISPLAYDEP) $(VECTDEP) $(DBMIDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
