MODULE_TOPDIR = ../..

PGM = xganim

EXTRA_CFLAGS=$(XCFLAGS) $(XMINC)

LIBES = $(GISLIB) $(XLIBPATH) $(XMLIB) $(XTLIB) $(XLIB) $(XEXTRALIBS)
DEPENDENCIES = $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
