MODULE_TOPDIR = ..

SUBDIRS = \
	d.correlate \
	d.polar \
	d.rast.edit \
	d.rast.leg \
	d.shadedmap \
	db.dropcol \
	db.droptable \
	db.in.ogr \
	db.out.ogr \
	db.test \
	g.manual \
	i.fusion.brovey \
	i.image.mosaic \
	i.in.spotvgt \
	i.landsat.rgb \
	i.oif \
	i.spectral \
	i.tasscap \
	m.proj \
	r.blend \
	r.buffer \
	r.colors.stddev \
	r.fillnulls \
	r.grow \
	r.in.aster \
	r.in.srtm \
	r.in.wms \
	r.mask \
	r.out.xyz \
	r.plane \
	r.reclass.area \
	r.regression.line \
	r.shaded.relief \
	r.tileset \
	v.build.all \
	v.centroids \
	v.colors \
	v.convert.all \
	v.db.addcol \
	v.db.addtable \
	v.db.join \
	v.db.dropcol \
	v.db.droptable \
	v.db.renamecol \
	v.db.reconnect.all \
	v.db.univar \
	v.db.update \
	v.dissolve \
	v.in.e00 \
	v.in.garmin \
	v.in.geonames \
	v.in.gns \
	v.in.gpsbabel \
	v.in.mapgen \
	v.in.sites.all \
	v.in.wfs \
	v.out.gps \
	v.rast.stats \
	v.report \
	v.to.3d \
	v.what.vect

#	d.vect.thematic \
#	d.out.gpsdrive \
#	r.mapcalculator \
#	r3.mapcalculator \

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs

