MODULE_TOPDIR = ../..

PGM = i.class

LIBES     = $(IMAGERYLIB) $(DISPLAYLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES= $(IMAGERYDEP) $(DISPLAYDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
