MODULE_TOPDIR = ../..

PGM = v.buffer

LIBES = $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES= $(VECTDEP) $(DBMIDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd

