MODULE_TOPDIR = ../..

PGM = r.in.wms

ETCFILES = wms_base wms_drv wms_gdal_drv wms_cap_parsers

include $(MODULE_TOPDIR)/include/Make/Script.make
include $(MODULE_TOPDIR)/include/Make/Python.make

default: script
