#!/bin/sh

usage()
{
    cat <<EOF
Usage: geos-config [OPTIONS]
Options:
     [--prefix]
     [--version]
     [--libs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--jtsport]
EOF
    exit $1
}
if test $# -eq 0; then
  usage 1 1>&2
fi
while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac
case $1 in
    --prefix)
    echo $OSGEO4W_ROOT_MSYS
     ;;
    --version)
    echo 3.2.2
     ;;
    --cflags)
    echo -I$OSGEO4W_ROOT_MSYS/include
      ;;
    --libs)
      echo $OSGEO4W_ROOT_MSYS/lib/geos_c.lib
      ;;
    --ldflags)
      echo 
      ;;
    --includes)
      echo $OSGEO4W_ROOT_MSYS/include
      ;;
    --jtsport)
    echo 1.10.0 
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done


