del "%OSGEO4W_STARTMENU%\GRASS GIS @VERSION@\GRASS GUI.lnk"
del "%OSGEO4W_STARTMENU%\GRASS GIS @VERSION@\GRASS Command Line.lnk"
rmdir "%OSGEO4W_STARTMENU%\GRASS GIS @VERSION@" 

del "%ALLUSERSPROFILE%\Desktop\GRASS GIS @VERSION@.lnk"

del "%OSGEO4W_ROOT%"\apps\grass\grass-@VERSION@\etc\fontcap
del "%OSGEO4W_ROOT%"\bin\grass@POSTFIX@.bat
del "%OSGEO4W_ROOT%"\bin\grass@POSTFIX@
