MODULE_TOPDIR = ../..

PGM = r.geomorphon

LIBES = $(RASTERLIB) $(GISLIB) $(MATHLIB) $(PARSONLIB)
DEPENDENCIES = $(RASTERDEP) $(GISDEP) $(PARSONDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
