
MODULE_TOPDIR = ../..

PGM = v.normal

LIBES = $(VECTLIB) $(CDHCLIB) $(GISLIB)
DEPENDENCIES= $(VECTDEP) $(CDHCDEP) $(GISDEP) 
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
