
MODULE_TOPDIR = ../..

PGM=v.what.rast

LIBES     = $(VECTLIB) $(GISLIB) $(RASTERLIB)
DEPENDENCIES = $(VECTDEP) $(GISDEP) $(RASTERDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)
 
include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	

