MODULE_TOPDIR = ../../..

PGM=test.gpde.lib

LIBES = $(GISLIB) $(RASTER3DLIB) $(GPDELIB) $(GMATHLIB)
DEPENDENCIES = $(GISDEP) $(RASTER3DDEP) $(GPDEDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
