MODULE_TOPDIR = ../..

PGM = i.gensig

LIBES = $(IMAGERYLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(IMAGERYDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
