MODULE_TOPDIR = ../../..

PGM = modcats

LIBES = $(GISLIB) $(EDITLIB) $(VASKLIB) $(CURSES)
DEPENDENCIES = $(GISDEP) $(EDITDEP) $(VASKDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: etc

htmletc:
	@echo "No docs to generate."
