MODULE_TOPDIR = ../..

PGM = r.spreadpath

LIBES = $(SEGMENTLIB) $(RASTERLIB) $(GISLIB)
DEPENDENCIES = $(SEGMENTDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
