MODULE_TOPDIR = ../..

PGM = d.what.vect

LIBES        = $(DISPLAYLIB) $(VECTORLIB) $(DBMILIB) $(GISLIB)

DEPENDENCIES = $(DISPLAYDEP) $(VECTORDEP) $(DBMIDEP) $(GISDEP)

EXTRA_CFLAGS = $(VECT_CFLAGS)
EXTRA_INC = $(VECT_INC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




