MODULE_TOPDIR = ../..

PGM = d.title

LIBES     = $(DISPLAYLIB) $(GISLIB) $(RASTELIB)
DEPENDENCIES= $(DISPLAYDEP) $(GISDEP) $(RASTERDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
