MODULE_TOPDIR = ../..

PGM = g.proj

EXTRA_INC = $(PROJINC)
LIBES     = $(PROJLIB) $(GPROJLIB) $(GISLIB)
DEPENDENCIES= $(GPROJDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
