MODULE_TOPDIR = ../..

EXTRA_LIBS = $(OMPLIB)
EXTRA_CFLAGS = $(FFTWINC) $(OMPCFLAGS)
# needed? $(OMPLIBPATH)

LIB = GMATH

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=gmath
