MODULE_TOPDIR = ../..

LIB = IMAGERY

EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make


default: lib

#doxygen:
DOXNAME=imagery
