MODULE_TOPDIR = ../..

PGM=r.gwflow

LIBES = $(GPDELIB) $(RASTERLIB) $(GISLIB) $(GMATHLIB)
DEPENDENCIES = $(GPDEDEP) $(RASTERDEP) $(GISDEP) $(GMATHDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
