
MODULE_TOPDIR = ../..

PGM = v.net.salesman

LIBES = $(VECTORLIB) $(GRAPHLIB) $(GISLIB)
DEPENDENCIES = $(VECTORDEP) $(GRAPHDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd




