MODULE_TOPDIR = ../..

PGM = v.rectify

LIBES = $(IMAGERYLIB) $(VECTORLIB) $(GISLIB)
DEPENDENCIES = $(IMAGERYDEP) $(VECTORDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
