void test1(double *a, int n);
void test2(double **a, int n, int m);
void test3(double ***a, int n, int m, int l);
void testd1(double *a, int n);
void testd2(double **a, int n, int m);
void testd3(double ***a, int n, int m, int l);
void testf1(float *a, int n);
void testf2(float **a, int n, int m);
void testf3(float ***a, int n, int m, int l);
void testi1(int *a, int n);
void testi2(int **a, int n, int m);
void testi3(int ***a, int n, int m, int l);
