MODULE_TOPDIR = ../..

LIB_NAME = $(G3D_LIBNAME)

EXTRA_LIBS = $(GISLIB) $(RASTRLIB)

include $(MODULE_TOPDIR)/include/Make/Lib.make
include $(MODULE_TOPDIR)/include/Make/Doxygen.make

default: lib

#doxygen:
DOXNAME=g3d
