MODULE_TOPDIR = ../..

PGM=r.solute.transport

LIBES = $(GISLIB) $(RASTERLIB) $(GPDELIB) $(GMATHLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(GMATHDEP) $(GPDEDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
