MODULE_TOPDIR = ../../..

EXTRA_LIBS=$(DBMIBASELIB) $(GISLIB)
EXTRA_CFLAGS = $(USE_DIRECT) $(USE_BUFFERED_IO) -I../dbmi_base

LIB_NAME = $(DBMICLIENT_LIBNAME)

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib




