name: Generate PGMS last commit json file

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Execute script
        working-directory: ./utils
        run: |
          python gen_pgms_last_commit.py ../

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "pgms_with_last_commit.json: update file"
          commit_user_name: GitHub Actions Bot # defaults to "GitHub Actions"
          commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          commit_author: Author <actions@github.com>
