---
name: Periodic update

on:
  workflow_dispatch:
    inputs:
      update_po:
        type: boolean
        default: false
        description: If true, also update .po files.
  schedule:
    - cron: "32 15 * * SAT"

permissions: {}

jobs:
  update-configure:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/${GITHUB_RUN_ID}" >> "${GITHUB_OUTPUT}"

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: false

      - name: "Check that autoconf scripts are up-to-date:"
        run: |
          rm -f config.guess config.sub
          wget http://git.savannah.gnu.org/cgit/config.git/plain/config.guess && chmod +x config.guess
          wget http://git.savannah.gnu.org/cgit/config.git/plain/config.sub && chmod +x config.sub

      - run: git diff -- config.guess config.sub
      - name: Double check if files are modified
        run: git status --ignored

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412
        with:
          commit-message: "config.guess + config.sub: updated from http://git.savannah.gnu.org/cgit/config.git/plain/"
          branch: periodic/update-configure
          title: "configure: update to latest config.guess and config.sub"
          body: |
            This updates config.guess and config.sub to their latest versions.
            If the two files are deleted in this PR, please check the logs of the workflow here:
            [Workflow run summary](${{ steps.vars.outputs.run-url }})

            Automated changes by create-pull-request GitHub action

  update-i18n:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    # 🔥 Prevent overlapping runs
    concurrency:
      group: periodic-i18n
      cancel-in-progress: false

    steps:
      - name: Create URL to the run output
        id: vars
        run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/${GITHUB_RUN_ID}" >> "${GITHUB_OUTPUT}"

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends --no-install-suggests \
            gettext \
            libgdal-dev \
            libproj-dev

      - name: Configure grass with minimal packages
        run: |
          ./configure \
            --with-nls \
            --without-cairo \
            --without-fftw \
            --without-freetype \
            --without-opengl \
            --without-pdal

      - name: Build grass core
        run: make -j"$(nproc)"

      - name: Create .pot files
        run: cd locale && make pot

      - name: Merge new messages
        if: ${{ inputs.update_po || false }}
        run: cd locale && make update-po

      - name: Verify the .po files
        run: cd locale && make verify

      - name: Preview changed files
        run: git diff | head -n2000

      - name: Preview changed files, except for the POT-Creation-Date
        run: |
          git diff --ignore-matching-lines=^\"POT-Creation-Date:  | head -n2000

      - name: Get if files were updated
        id: changed-files
        continue-on-error: true
        run: |
          git diff --exit-code --quiet --ignore-matching-lines=^\"POT-Creation-Date:

      - name: Translation files were changed
        if: ${{ steps.changed-files.outcome == 'failure' }}
        run: echo "Translation files were changed"

      - name: Translation files were not changed
        if: ${{ steps.changed-files.outcome == 'success' }}
        run: echo "Translation files were not changed"

      - name: Double check if files are modified
        run: git status --ignored

      - name: Create Pull Request
        if: ${{ steps.changed-files.outcome == 'failure' }}
        id: cpr
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412
        with:
          commit-message: "locale: Update translation files"
          branch: periodic/update-i18n-${{ github.run_id }}
          title: "locale: Update translation files (${{ github.run_number }})"
          body: |
            This updates the .pot template files, as well as all language-specific .po files
            if the option was selected.
            [Workflow run summary](${{ steps.vars.outputs.run-url }})

            Automated changes by create-pull-request GitHub action

      - name: Check outputs
        if: ${{ steps.changed-files.outcome == 'failure' && steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${STEPS_CPR_OUTPUTS_PULL_REQUEST_NUMBER}"
          echo "Pull Request URL - ${STEPS_CPR_OUTPUTS_PULL_REQUEST_URL}"
        env:
          STEPS_CPR_OUTPUTS_PULL_REQUEST_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
          STEPS_CPR_OUTPUTS_PULL_REQUEST_URL: ${{ steps.cpr.outputs.pull-request-url }}
