name: Track Dismissed Code Scanning Alerts

on:
  push:
    branches: 
     - dismissalCheckout   # Trigger only test branch

jobs:
    track-dismissals:
        runs-on: ubuntu-latest  # Replace with your preferred runner
     
        steps:
           - uses: actions/checkout@v3  # Checkout repository code
     
           - uses: actions/github-script@v6  # Use the actions/github-script action
             with:
               github-token: ${{ secrets.GITHUB_TOKEN }}
               script: |  # Multi-line script for code execution
                 // Fetch current code scanning alerts
                 const alerts = await github.issues.listForRepo({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   filter: 'security'
                 });

                 //only get dismissed alerts and print them to the consol
                 const dismissedAlerts = alerts.data.filter(alert => alert.dismissed);

                 // Log dismissed alerts
                 console.log(dismissedAlerts);
