name: Track Dismissed Code Scanning Alerts

on:
  push:
    branches: 
     - main
     - dismissalCheckout   # Trigger only test branch, remember to remove before PRing to grass

jobs:
    get-dismissals-data:
        runs-on: ubuntu-latest  
        permissions: write-all

        steps:
     
     
           - uses: actions/checkout@v4 # Checkout repository code
    
           - name: Install dependencies (if needed for parsing security tool response)
             run: |
                # Add any package installation commands here (e.g., pip install requests)
                 echo "Installing dependencies..."  # Placeholder
                 
   
           - name: Get Security Alerts
          
             run: |
             
              curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/ncsu-csc472-spring2024/grass-CI-playground/code-scanning/alerts > alerts.json  

              # remember to change the path above before uploading to grass!

              echo "Security Alerts retrieved successfully!"

              #trigger a rerun

           - name: Upload the coding alerts as artifact
             uses: actions/upload-artifact@v4
             with:
              name: workflow-data
              path: alerts.json


# get the repository issues 
           - name: Get Current Issues        
             run: |
              
               curl -L \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/ncsu-csc472-spring2024/grass-CI-playground/issues > issues.json  
 
               # remember to change the path above before uploading to grass!
 
               echo "issues retrieved successfully!"
 
               #trigger a rerun
 
           - name: Upload the issues as artifact
             uses: actions/upload-artifact@v4
             with:
                 name: issues-data
                 path: issues.json

    track-dismissals:
     runs-on: ubuntu-latest  
     permissions: write-all
              
     steps:
                   

     - name: Download artifacts
       uses: actions/download-artifact@v3
       with:
         name: issues-data  # Match the name used for upload
       
     - name: Download artifacts
       uses: actions/download-artifact@v3
       with:
         name: workflow-data

         
     - name: Use downloaded artifact
       run: |
         cat issues.json # Access the downloaded artifact
         cat alerts.json
          
       