name: Track Dismissed Code Scanning Alerts

on:
  push:
    branches: 
     - dismissalCheckout   # Trigger only test branch

jobs:
    track-dismissals:
        runs-on: ubuntu-latest  # Replace with your preferred runner
        permissions: write-all

        steps:
     
     
           - uses: actions/checkout@v4 # Checkout repository code
    
           - name: Install dependencies (if needed for parsing security tool response)
             run: |
                # Add any package installation commands here (e.g., pip install requests)
                 echo "Installing dependencies..."  # Placeholder
                 
   
           - name: Get Security Alerts
          
             run: |
             
              curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/ncsu-csc472-spring2024/grass-CI-playground/code-scanning/alerts
              echo "Security Alerts retrieved successfully!"

              #trigger a rerun