
MODULE_TOPDIR = ../..

LIB_NAME = $(DATETIME_LIBNAME)

LIB_OBJS =  \
	between.o \
	copy.o\
	same.o\
	diff.o\
	error.o \
	format.o\
	incr1.o\
	incr2.o\
	incr3.o\
	local.o\
	misc.o \
	change.o\
	scan.o\
	sign.o\
	type.o \
	tz1.o\
	tz2.o\
	values.o

include $(MODULE_TOPDIR)/include/Make/Lib.make

default: lib


# $(LIB_OBJS): $(INCLUDE_DIR)/datetime.h $(INCLUDE_DIR)/P_datetime.h

#proto:
#	make.proto *.c > P_datetime.h
