MODULE_TOPDIR = ..

SUBDIRS = \
	t.create \
	t.list \
	t.info \
	t.remove \
	t.time.abs \
	t.time.rel \
	tr.register \
	tr3.register \
	tv.register \
	tr.unregister \
	tr3.unregister \
	tv.unregister \

PGM = tgisintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

