MODULE_TOPDIR = ..

SUBDIRS = \
	t.create \
	t.support \
	t.topology \
	t.list \
	t.info \
	t.remove \
	t.sample \
	t.register \
	t.unregister \
	tr.aggregate \
	tr.aggregate.ds \
	tr.to.rast3 \
	tr.univar \
	tr.list \
	tr.series \
	tr.export \
	tr.out.vtk \
	tr.import \
	tr.extract \
	tr3.list \
	tr3.extract \
	tv.list \
	tv.what.strds \
	tv.observe.strds

PGM = tgisintro

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: htmldir

htmldir: parsubdirs

