MODULE_TOPDIR = ../..

PGM=r.to.vect

include $(MODULE_TOPDIR)/include/Make/Module.make

LIBES     = $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)

default: cmd	

