/* sun11.c */
int INPUT(void);
int OUTGR(void);
double amax1(double, double);
double amin1(double, double);
int min(int, int);
int max(int, int);
void com_par(void);
double lumcline2(void);
double joules2(void);
int quadrant(void);
double coef_of_line(void);
void new_point_x(int, double *, double *, double *);
void new_point_y(int, double *, double *, double *);
void which_one(double, double, double, double, double, double);
int combine_x(int, int, int, int);
int combine_y(int, int, int, int);
int vertex(int, int);
int mesh_vertex(void);
int mesh_line(void);
void calculate(void);
double com_sol_const(void);
double com_declin(int);
