MODULE_TOPDIR = ../..

PGM=v.to.3d

LIBES = $(VECTLIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(VECTDEP) $(DBMIDEP) $(GISDEP)
EXTRA_CFLAGS = $(VECT_CFLAGS)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd	
